global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'Roshambr Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['roshambr:8080']
        labels:
          application: 'Roshambr'